### PR TITLE
Update express routing

### PR DESCRIPTION
**Pull request by BrianMouraJr**
deleted redundancies, organized index.js in api folder, organized index.js in controllers folder

### CODE REVIEW

**Comment by bootcampp2g9** [comment]
looks good

**Review by gerikoci31 — APPROVED** [review]
looks good

**Review by gerikoci31 — APPROVED** [review]
looks good andrew

**Review by DrewRic — DISMISSED** [review]

**Comment by DrewRic** [comment]
Closed due to an unresolved conflict

**Pull request closed without merging**
